---
language: python
python: "2.7"
sudo: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
script:
  - ansible-playbook -i inventory role.yml -e envconsul_bin_path=/home/travis/
